DirInputs: .........../InputsData/
DirOutputs : ....... /Outputs/
DataSpreadsheet : Data&Values.xlsx
FilePlots: Plots.tif
DataPlots: LandUse_TimeSeries.txt
RasterNoDataValue : -99999
DataRainfall: Rainfall_TimeSeries.xlsx
DataRainfallEvent : Rainfall_EventsCharacteristics.xlsx